version: '3'

services:
  app:
    build: .
    ports:
      - 3001:3001
    volumes:
      - .:/home/node/app
    depends_on:
      - rabbitmq
    environment:
      - API_URL=http://app:3001

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
